# Generated by Django 5.2.4 on 2025-08-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunningActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_date", models.DateField(verbose_name="Activity date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "pace",
                    models.DurationField(blank=True, null=True, verbose_name="Pace"),
                ),
                (
                    "heart_rate_avg",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Average heart rate"
                    ),
                ),
                (
                    "heart_rate_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Maximum heart rate"
                    ),
                ),
                (
                    "ascent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ascent",
                    ),
                ),
                (
                    "descent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Descent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Running activity",
                "verbose_name_plural": "Running activities",
                "ordering": ["-activity_date"],
                "abstract": False,
            },
        ),
    ]
